import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'tr' | 'en' | 'de' | 'es' | 'ru' | 'zh' | 'ku';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  tr: {
    // Home Screen
    'home.welcome': 'Tekrar hoşgeldin,',
    'home.guest': 'Misafir',
    'home.friends_active': 'arkadaşın aktif',
    'home.quick_access': 'Hızlı Erişim',
    'home.privileges': 'Ayrıcalıklar',
    'home.chat_rooms': 'Sohbet Odaları',
    'home.chat_rooms_desc': 'Genel sohbetlere katıl veya özel şifreli odalar oluştur',
    'home.study_sessions': 'Çalışma Oturumları',
    'home.study_sessions_desc': 'Çalışma süresini takip et ve arkadaşlarınla yarış',
    'home.watch_room': 'Watch Room',
    'home.watch_room_desc': 'Arkadaşlarınla beraber video izle ve sohbet et',
    'home.ai_coach': 'Eğitim Koçum',
    'home.ai_study': 'Yapay Zeka ile Çalış',
    'home.ai_coach_desc': 'Yapay zeka destekli eğitim asistanınız size yardımcı olmak için hazır',
    'home.ai_study_desc': 'Yapay zeka destekli eğitim koçu ve soru çözüm asistanı ile çalışmalarını daha verimli hale getir',
    'home.upgrade_pro': 'Pro\'ya Yükselt',

    // Profile Screen
    'profile.user': 'Kullanıcı',
    'profile.rookie': 'Çaylak',
    'profile.student': 'Öğrenci',
    'profile.professor': 'Profesör',
    'profile.level': 'Seviye',
    'profile.xp_left': 'XP kaldı',
    'profile.my_stats': 'İstatistiklerim',
    'profile.study_hours': 'Çalışma Saati',
    'profile.messages': 'Mesajlar',
    'profile.achievements': 'Başarımlar',
    'profile.this_week': 'Bu hafta',
    'profile.new': 'Yeni',
    'profile.account_settings': 'Hesap Ayarları',
    'profile.account_info': 'Hesap Ayarları',
    'profile.notifications': 'Bildirimler',
    'profile.upgrade_pro': 'Pro\'ya Yükselt',
    'profile.app_settings': 'Uygulama Ayarları',
    'profile.theme_settings': 'Tema ayarları',
    'profile.language_options': 'Dil Seçenekleri',
    'profile.help_support': 'Yardım & Destek',
    'profile.other': 'Diğer',
    'profile.logout': 'Çıkış Yap',

    // Account Settings
    'account.title': 'Hesap Ayarları',
    'account.profile_info': 'Profil Bilgileri',
    'account.personal_info': 'Kişisel Bilgiler',
    'account.full_name': 'İsim Soyisim',
    'account.enter_name': 'İsminizi girin',
    'account.update_profile': 'Profili Güncelle',
    'account.security': 'Güvenlik',
    'account.change_password': 'Şifre Değiştir',
    'account.new_password': 'Yeni Şifre',
    'account.enter_new_password': 'Yeni şifrenizi girin',
    'account.confirm_password': 'Şifre Tekrarı',
    'account.enter_confirm_password': 'Yeni şifrenizi tekrar girin',
    'account.update_password': 'Şifreyi Güncelle',
    'account.profile_updated': 'Profil başarıyla güncellendi',
    'account.password_updated': 'Şifre başarıyla güncellendi',
    'account.passwords_not_match': 'Yeni şifreler eşleşmiyor',
    'account.password_min_length': 'Şifre en az 6 karakter olmalıdır',
    'account.loading_error': 'Profil bilgileri yüklenirken bir hata oluştu',

    // Language Modal
    'language.select_language': 'Dil Seçin',
    'language.select_app_language': 'Uygulama dilini seçin',
    'language.turkish': 'Türkçe',
    'language.english': 'İnglizce',
    'language.german': 'Almanca',
    'language.spanish': 'İspanyolca',
    'language.russian': 'Rusça',
    'language.chinese': 'Çince',
    'language.kurdish': 'Kürtçe',
    'language.cancel': 'İptal',

    // Common
    'common.cancel': 'İptal',
    'common.save': 'Kaydet',
    'common.loading': 'Yükleniyor...',
    'common.error': 'Hata',
    'common.success': 'Başarılı',
    'common.delete': 'Sil',
    'common.edit': 'Düzenle',
    'common.back': 'Geri',
    'common.next': 'İleri',
    'common.yes': 'Evet',
    'common.no': 'Hayır',
    'common.ok': 'Tamam',

    // AI Chat
    'ai_chat.title': 'EĞİTİM KOÇUM',
    'ai_chat.greeting': 'Merhaba! Ben senin yapay zeka destekli eğitim koçunum. Ders çalışma, sınavlara hazırlanma veya herhangi bir konuda sana yardımcı olabilirim. Seni daha iyi tanıyabilir miyim?',
    'ai_chat.type_message': 'Mesajınızı yazın...',
    'ai_chat.send': 'Gönder',
    'ai_chat.clear_chat': 'Sohbeti Temizle',
    'ai_chat.attach_image': 'Resim Ekle',
    'ai_chat.take_photo': 'Fotoğraf Çek',
    'ai_chat.attach_file': 'Dosya Ekle',
    'ai_chat.thinking': 'Düşünüyor...',
    'ai_chat.error_message': 'Bir hata oluştu. Lütfen tekrar deneyin.',

    // Chat Rooms
    'chat.title': 'Sohbet Odaları',
    'chat.public_rooms': 'Genel Odalar',
    'chat.private_rooms': 'Özel Odalar',
    'chat.create_room': 'Oda Oluştur',
    'chat.join_room': 'Odaya Katıl',
    'chat.room_name': 'Oda Adı',
    'chat.room_description': 'Oda Açıklaması',
    'chat.room_password': 'Oda Şifresi',
    'chat.is_private': 'Özel Oda',
    'chat.active_room': 'Aktif Oda',
    'chat.encrypted': 'Şifreli',
    'chat.members': 'üye',
    'chat.search_rooms': 'Oda ara...',
    'chat.no_rooms': 'Bu kategoride henüz oda yok',
    'chat.delete_room': 'Odayı Sil',
    'chat.leave_room': 'Odadan Ayrıl',
    'chat.enter_password': 'Şifre girin',

    // Study Rooms
    'study.title': 'Çalışma Odaları',
    'study.personal_timer': 'Kişisel Zamanlayıcı',
    'study.create_room': 'Çalışma Odası Oluştur',
    'study.join_room': 'Odaya Katıl',
    'study.start_timer': 'Başla',
    'study.pause_timer': 'Duraklat',
    'study.resume_timer': 'Devam Et',
    'study.stop_timer': 'Durdur',
    'study.reset_timer': 'Sıfırla',
    'study.study_session': 'Çalışma Oturumu',
    'study.total_time': 'Toplam Süre',
    'study.active_members': 'aktif',
    'study.room_description': 'Çalışma odası',
    'study.private_room': 'Özel Oda',
    'study.public_rooms': 'Genel Odalar',
    'study.private_rooms': 'Özel Odalar',
    'study.no_rooms': 'Bu kategoride henüz oda yok',

    // Help & Support
    'help.title': 'Yardım & Destek',
    'help.welcome_title': 'Size Nasıl Yardımcı Olabiliriz?',
    'help.welcome_desc': 'Herhangi bir sorunuz veya sorununuz mu var? Size yardımcı olmaktan mutluluk duyarız. Aşağıdaki kanallardan bizimle iletişime geçebilirsiniz.',
    'help.email': 'E-posta',
    'help.live_support': 'Canlı Destek',
    'help.live_support_desc': '7/24 Chat Desteği',
    'help.website': 'Website',
    'help.phone': 'Telefon',
    'help.faq_title': 'Sıkça Sorulan Sorular',
    'help.faq_1_q': 'AI Koç nasıl çalışır?',
    'help.faq_1_a': 'AI Koçumuz, sorularınızı analiz ederek kişiselleştirilmiş eğitim önerileri sunar. Ders çalışma planları oluşturur ve konuları anlamanıza yardımcı olur.',
    'help.faq_2_q': 'Çalışma odaları nasıl kullanılır?',
    'help.faq_2_a': 'Çalışma odalarına katılarak arkadaşlarınızla birlikte çalışabilir, süre takibi yapabilir ve birlikte motivasyon sağlayabilirsiniz.',
    'help.faq_3_q': 'Pro üyelik ne avantajlar sağlar?',
    'help.faq_3_a': 'Pro üyelikle sınırsız AI koçluk, premium çalışma odaları, gelişmiş istatistikler ve reklamsız deneyim elde edersiniz.',
    'help.faq_4_q': 'Verilerim güvende mi?',
    'help.faq_4_a': 'Evet, tüm verileriniz 256-bit SSL şifreleme ile korunur. Kişisel bilgilerinizi asla üçüncü taraflarla paylaşmayız.',
    'help.faq_5_q': 'Hangi konularda yardım alabilirim?',
    'help.faq_5_a': 'Matematik, fen bilimleri, dil bilgisi, tarih ve daha birçok konuda AI koçumuzdan yardım alabilirsiniz.',

    // Payment
    'payment.title': 'Ödeme',
    'payment.pro_title': 'Roomix Pro',
    'payment.premium_features': 'Premium özelliklerin keyfini çıkarın',
    'payment.monthly_subscription': 'Aylık abonelik',
    'payment.yearly_subscription': 'Yıllık abonelik',
    'payment.per_year': '/yıl',
    'payment.features.unlimited_ai': 'Sınırsız AI Koçluk',
    'payment.features.premium_rooms': 'Premium Çalışma Odaları',
    'payment.features.advanced_stats': 'Gelişmiş İstatistikler',
    'payment.features.ad_free': 'Reklamsız Deneyim',
    'payment.features.priority_support': 'Öncelikli Destek',
    'payment.card_info': 'Ödeme Bilgileri',
    'payment.card_holder': 'Kart Sahibinin Adı',
    'payment.card_number': 'Kart Numarası',
    'payment.expiry_date': 'Son Kullanma Tarihi',
    'payment.cvc': 'CVC',
    'payment.complete_payment': 'Ödemeyi Tamamla',
    'payment.processing': 'İşleniyor...',
    'payment.success_title': 'Ödeme Başarılı! 🎉',
    'payment.success_message': 'Pro üyeliğiniz aktifleştirildi.',
    'payment.error_title': 'Ödeme Hatası',
    'payment.error_message': 'Ödeme işlemi başarısız oldu. Lütfen tekrar deneyin.',
    'payment.fill_all_fields': 'Lütfen tüm alanları doldurun',
    'payment.valid_card_number': 'Geçerli bir kart numarası girin',
    'payment.security_info': '256-bit SSL şifreleme ile güvenli ödeme',

    // Watch Rooms
    'watch.title': 'Watch Room',
    'watch.create_room': 'Watch Room Oluştur',
    'watch.join_room': 'Odaya Katıl',
    'watch.video_url': 'Video URL\'si',
    'watch.sync_video': 'Video Senkronize Et',
    'watch.play': 'Oynat',
    'watch.pause': 'Duraklat',
    'watch.members_watching': 'kişi izliyor',
  },
  en: {
    // Home Screen
    'home.welcome': 'Welcome back,',
    'home.guest': 'Guest',
    'home.friends_active': 'friends active',
    'home.quick_access': 'Quick Access',
    'home.privileges': 'Privileges',
    'home.chat_rooms': 'Chat Rooms',
    'home.chat_rooms_desc': 'Join public chats or create private encrypted rooms',
    'home.study_sessions': 'Study Sessions',
    'home.study_sessions_desc': 'Track study time and compete with friends',
    'home.watch_room': 'Watch Room',
    'home.watch_room_desc': 'Watch videos together with friends and chat',
    'home.ai_coach': 'My AI Coach',
    'home.ai_study': 'Study with AI',
    'home.ai_coach_desc': 'Your AI-powered education assistant is ready to help you',
    'home.ai_study_desc': 'Make your studies more efficient with AI-powered education coach and problem-solving assistant',
    'home.upgrade_pro': 'Upgrade to Pro',

    // Profile Screen
    'profile.user': 'User',
    'profile.rookie': 'Rookie',
    'profile.student': 'Student',
    'profile.professor': 'Professor',
    'profile.level': 'Level',
    'profile.xp_left': 'XP left',
    'profile.my_stats': 'My Statistics',
    'profile.study_hours': 'Study Hours',
    'profile.messages': 'Messages',
    'profile.achievements': 'Achievements',
    'profile.this_week': 'This week',
    'profile.new': 'New',
    'profile.account_settings': 'Account Settings',
    'profile.account_info': 'Account Information',
    'profile.notifications': 'Notifications',
    'profile.upgrade_pro': 'Upgrade to Pro',
    'profile.app_settings': 'App Settings',
    'profile.theme_settings': 'Theme Settings',
    'profile.language_options': 'Language Options',
    'profile.help_support': 'Help & Support',
    'profile.other': 'Other',
    'profile.logout': 'Logout',

    // Account Settings
    'account.title': 'Account Settings',
    'account.profile_info': 'Profile Information',
    'account.personal_info': 'Personal Information',
    'account.full_name': 'Full Name',
    'account.enter_name': 'Enter your name',
    'account.update_profile': 'Update Profile',
    'account.security': 'Security',
    'account.change_password': 'Change Password',
    'account.new_password': 'New Password',
    'account.enter_new_password': 'Enter your new password',
    'account.confirm_password': 'Confirm Password',
    'account.enter_confirm_password': 'Re-enter your new password',
    'account.update_password': 'Update Password',
    'account.profile_updated': 'Profile updated successfully',
    'account.password_updated': 'Password updated successfully',
    'account.passwords_not_match': 'New passwords do not match',
    'account.password_min_length': 'Password must be at least 6 characters',
    'account.loading_error': 'An error occurred while loading profile information',

    // Language Modal
    'language.select_language': 'Select Language',
    'language.select_app_language': 'Choose your application language',
    'language.turkish': 'Turkish',
    'language.english': 'English',
    'language.german': 'German',
    'language.spanish': 'Spanish',
    'language.russian': 'Russian',
    'language.chinese': 'Chinese',
    'language.kurdish': 'Kurdish',
    'language.cancel': 'Cancel',

    // Common
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',

    // AI Chat
    'ai_chat.title': 'AI Coach',
    'ai_chat.greeting': 'Hello! I am your AI-powered education coach. I can help you with studying, exam preparation, or any topic. Can I get to know you better?',
    'ai_chat.type_message': 'Type your message...',
    'ai_chat.send': 'Send',
    'ai_chat.clear_chat': 'Clear Chat',
    'ai_chat.attach_image': 'Attach Image',
    'ai_chat.take_photo': 'Take Photo',
    'ai_chat.attach_file': 'Attach File',
    'ai_chat.thinking': 'Thinking...',
    'ai_chat.error_message': 'An error occurred. Please try again.',

    // Chat Rooms
    'chat.title': 'Chat Rooms',
    'chat.public_rooms': 'Public Rooms',
    'chat.private_rooms': 'Private Rooms',
    'chat.create_room': 'Create Room',
    'chat.join_room': 'Join Room',
    'chat.room_name': 'Room Name',
    'chat.room_description': 'Room Description',
    'chat.room_password': 'Room Password',
    'chat.is_private': 'Private Room',
    'chat.active_room': 'Active Room',
    'chat.encrypted': 'Encrypted',
    'chat.members': 'members',
    'chat.search_rooms': 'Search rooms...',
    'chat.no_rooms': 'No rooms in this category yet',
    'chat.delete_room': 'Delete Room',
    'chat.leave_room': 'Leave Room',
    'chat.enter_password': 'Enter password',

    // Study Rooms
    'study.title': 'Study Rooms',
    'study.personal_timer': 'Personal Timer',
    'study.create_room': 'Create Study Room',
    'study.join_room': 'Join Room',
    'study.start_timer': 'Start',
    'study.pause_timer': 'Pause',
    'study.resume_timer': 'Resume',
    'study.stop_timer': 'Stop',
    'study.reset_timer': 'Reset',
    'study.study_session': 'Study Session',
    'study.total_time': 'Total Time',
    'study.active_members': 'active',
    'study.room_description': 'Study room',
    'study.private_room': 'Private Room',
    'study.public_rooms': 'Public Rooms',
    'study.private_rooms': 'Private Rooms',
    'study.no_rooms': 'No rooms in this category yet',

    // Help & Support
    'help.title': 'Help & Support',
    'help.welcome_title': 'How Can We Help You?',
    'help.welcome_desc': 'Do you have any questions or issues? We would be happy to help you. You can contact us through the channels below.',
    'help.email': 'Email',
    'help.live_support': 'Live Support',
    'help.live_support_desc': '24/7 Chat Support',
    'help.website': 'Website',
    'help.phone': 'Phone',
    'help.faq_title': 'Frequently Asked Questions',
    'help.faq_1_q': 'How does AI Coach work?',
    'help.faq_1_a': 'Our AI Coach analyzes your questions and provides personalized educational recommendations. It creates study plans and helps you understand topics.',
    'help.faq_2_q': 'How to use study rooms?',
    'help.faq_2_a': 'By joining study rooms, you can study together with friends, track time, and maintain motivation together.',
    'help.faq_3_q': 'What benefits does Pro membership provide?',
    'help.faq_3_a': 'With Pro membership, you get unlimited AI coaching, premium study rooms, advanced statistics, and an ad-free experience.',
    'help.faq_4_q': 'Is my data safe?',
    'help.faq_4_a': 'Yes, all your data is protected with 256-bit SSL encryption. We never share your personal information with third parties.',
    'help.faq_5_q': 'What subjects can I get help with?',
    'help.faq_5_a': 'You can get help from our AI coach on mathematics, science, language arts, history, and many other subjects.',

    // Payment
    'payment.title': 'Payment',
    'payment.pro_title': 'Roomix Pro',
    'payment.premium_features': 'Enjoy premium features',
    'payment.monthly_subscription': 'Monthly subscription',
    'payment.yearly_subscription': 'Annual subscription',
    'payment.per_year': '/year',
    'payment.features.unlimited_ai': 'Unlimited AI Coaching',
    'payment.features.premium_rooms': 'Premium Study Rooms',
    'payment.features.advanced_stats': 'Advanced Statistics',
    'payment.features.ad_free': 'Ad-Free Experience',
    'payment.features.priority_support': 'Priority Support',
    'payment.card_info': 'Payment Information',
    'payment.card_holder': 'Cardholder Name',
    'payment.card_number': 'Card Number',
    'payment.expiry_date': 'Expiry Date',
    'payment.cvc': 'CVC',
    'payment.complete_payment': 'Complete Payment',
    'payment.processing': 'Processing...',
    'payment.success_title': 'Payment Successful! 🎉',
    'payment.success_message': 'Your Pro membership has been activated.',
    'payment.error_title': 'Payment Error',
    'payment.error_message': 'Payment failed. Please try again.',
    'payment.fill_all_fields': 'Please fill in all fields',
    'payment.valid_card_number': 'Enter a valid card number',
    'payment.security_info': 'Secure payment with 256-bit SSL encryption',

    // Watch Rooms
    'watch.title': 'Watch Room',
    'watch.create_room': 'Create Watch Room',
    'watch.join_room': 'Join Room',
    'watch.video_url': 'Video URL',
    'watch.sync_video': 'Sync Video',
    'watch.play': 'Play',
    'watch.pause': 'Pause',
    'watch.members_watching': 'people watching',
  },
  de: {
    // Home Screen
    'home.welcome': 'Willkommen zurück,',
    'home.guest': 'Gast',
    'home.friends_active': 'Freunde aktiv',
    'home.quick_access': 'Schnellzugriff',
    'home.privileges': 'Privilegien',
    'home.chat_rooms': 'Chatrooms',
    'home.chat_rooms_desc': 'Tritt öffentlichen Chats bei oder erstelle private verschlüsselte Räume',
    'home.study_sessions': 'Lernsitzungen',
    'home.study_sessions_desc': 'Verfolge deine Lernzeit und konkurriere mit Freunden',
    'home.watch_room': 'Watch Room',
    'home.watch_room_desc': 'Schaue Videos zusammen mit Freunden und chatte',
    'home.ai_coach': 'Mein KI-Coach',
    'home.ai_study': 'Mit KI lernen',
    'home.ai_coach_desc': 'Dein KI-gestützter Bildungsassistent ist bereit, dir zu helfen',
    'home.ai_study_desc': 'Mache dein Lernen effizienter mit KI-gestütztem Bildungscoach und Problemlösungsassistent',
    'home.upgrade_pro': 'Auf Pro upgraden',

    // Profile Screen
    'profile.user': 'Benutzer',
    'profile.rookie': 'Anfänger',
    'profile.student': 'Student',
    'profile.professor': 'Professor',
    'profile.level': 'Level',
    'profile.xp_left': 'XP übrig',
    'profile.my_stats': 'Meine Statistiken',
    'profile.study_hours': 'Lernstunden',
    'profile.messages': 'Nachrichten',
    'profile.achievements': 'Erfolge',
    'profile.this_week': 'Diese Woche',
    'profile.new': 'Neu',
    'profile.account_settings': 'Kontoeinstellungen',
    'profile.account_info': 'Kontoinformationen',
    'profile.notifications': 'Benachrichtigungen',
    'profile.upgrade_pro': 'Auf Pro upgraden',
    'profile.app_settings': 'App-Einstellungen',
    'profile.theme_settings': 'Design-Einstellungen',
    'profile.language_options': 'Sprachoptionen',
    'profile.help_support': 'Hilfe & Support',
    'profile.other': 'Sonstiges',
    'profile.logout': 'Abmelden',

    // Account Settings
    'account.title': 'Kontoeinstellungen',
    'account.profile_info': 'Profilinformationen',
    'account.personal_info': 'Persönliche Informationen',
    'account.full_name': 'Vollständiger Name',
    'account.enter_name': 'Geben Sie Ihren Namen ein',
    'account.update_profile': 'Profil aktualisieren',
    'account.security': 'Sicherheit',
    'account.change_password': 'Passwort ändern',
    'account.new_password': 'Neues Passwort',
    'account.enter_new_password': 'Geben Sie Ihr neues Passwort ein',
    'account.confirm_password': 'Passwort bestätigen',
    'account.enter_confirm_password': 'Geben Sie Ihr neues Passwort erneut ein',
    'account.update_password': 'Passwort aktualisieren',
    'account.profile_updated': 'Profil erfolgreich aktualisiert',
    'account.password_updated': 'Passwort erfolgreich aktualisiert',
    'account.passwords_not_match': 'Die neuen Passwörter stimmen nicht überein',
    'account.password_min_length': 'Das Passwort muss mindestens 6 Zeichen lang sein',
    'account.loading_error': 'Fehler beim Laden der Profilinformationen',

    // Language Modal
    'language.select_language': 'Sprache auswählen',
    'language.select_app_language': 'Wählen Sie Ihre Anwendungssprache',
    'language.turkish': 'Türkisch',
    'language.english': 'Englisch',
    'language.german': 'Deutsch',
    'language.spanish': 'Spanisch',
    'language.russian': 'Russisch',
    'language.chinese': 'Chinesisch',
    'language.kurdish': 'Kurdisch',
    'language.cancel': 'Abbrechen',

    // Common
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolgreich',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.yes': 'Ja',
    'common.no': 'Nein',
    'common.ok': 'OK',

    // AI Chat
    'ai_chat.title': 'KI-Coach',
    'ai_chat.greeting': 'Hallo! Ich bin dein KI-gestützter Bildungscoach. Ich kann dir beim Lernen, bei der Prüfungsvorbereitung oder bei jedem anderen Thema helfen. Kann ich dich besser kennenlernen?',
    'ai_chat.type_message': 'Nachricht eingeben...',
    'ai_chat.send': 'Senden',
    'ai_chat.clear_chat': 'Chat löschen',
    'ai_chat.attach_image': 'Bild anhängen',
    'ai_chat.take_photo': 'Foto aufnehmen',
    'ai_chat.attach_file': 'Datei anhängen',
    'ai_chat.thinking': 'Denkt nach...',
    'ai_chat.error_message': 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.',

    // Chat Rooms
    'chat.title': 'Chatrooms',
    'chat.public_rooms': 'Öffentliche Räume',
    'chat.private_rooms': 'Private Räume',
    'chat.create_room': 'Raum erstellen',
    'chat.join_room': 'Raum beitreten',
    'chat.room_name': 'Raumname',
    'chat.room_description': 'Raumbeschreibung',
    'chat.room_password': 'Raumpasswort',
    'chat.is_private': 'Privater Raum',
    'chat.active_room': 'Aktiver Raum',
    'chat.encrypted': 'Verschlüsselt',
    'chat.members': 'Mitglieder',
    'chat.search_rooms': 'Räume suchen...',
    'chat.no_rooms': 'Noch keine Räume in dieser Kategorie',
    'chat.delete_room': 'Raum löschen',
    'chat.leave_room': 'Raum verlassen',
    'chat.enter_password': 'Passwort eingeben',

    // Study Rooms
    'study.title': 'Lernräume',
    'study.personal_timer': 'Persönlicher Timer',
    'study.create_room': 'Lernraum erstellen',
    'study.join_room': 'Raum beitreten',
    'study.start_timer': 'Starten',
    'study.pause_timer': 'Pausieren',
    'study.resume_timer': 'Fortsetzen',
    'study.stop_timer': 'Stoppen',
    'study.reset_timer': 'Zurücksetzen',
    'study.study_session': 'Lernsitzung',
    'study.total_time': 'Gesamtzeit',
    'study.active_members': 'aktiv',
    'study.room_description': 'Lernraum',
    'study.private_room': 'Privater Raum',
    'study.public_rooms': 'Öffentliche Räume',
    'study.private_rooms': 'Private Räume',
    'study.no_rooms': 'Noch keine Räume in dieser Kategorie',

    // Help & Support
    'help.title': 'Hilfe & Support',
    'help.welcome_title': 'Wie können wir Ihnen helfen?',
    'help.welcome_desc': 'Haben Sie Fragen oder Probleme? Wir helfen Ihnen gerne. Sie können uns über die folgenden Kanäle kontaktieren.',
    'help.email': 'E-Mail',
    'help.live_support': 'Live-Support',
    'help.live_support_desc': '24/7 Chat-Support',
    'help.website': 'Website',
    'help.phone': 'Telefon',
    'help.faq_title': 'Häufig gestellte Fragen',
    'help.faq_1_q': 'Wie funktioniert der KI-Coach?',
    'help.faq_1_a': 'Unser KI-Coach analysiert Ihre Fragen und bietet personalisierte Bildungsempfehlungen. Er erstellt Lernpläne und hilft Ihnen, Themen zu verstehen.',
    'help.faq_2_q': 'Wie benutzt man Lernräume?',
    'help.faq_2_a': 'Durch das Beitreten zu Lernräumen können Sie mit Freunden zusammen lernen, Zeit verfolgen und gemeinsam motiviert bleiben.',
    'help.faq_3_q': 'Welche Vorteile bietet die Pro-Mitgliedschaft?',
    'help.faq_3_a': 'Mit der Pro-Mitgliedschaft erhalten Sie unbegrenztes KI-Coaching, Premium-Lernräume, erweiterte Statistiken und eine werbefreie Erfahrung.',
    'help.faq_4_q': 'Sind meine Daten sicher?',
    'help.faq_4_a': 'Ja, alle Ihre Daten sind mit 256-Bit-SSL-Verschlüsselung geschützt. Wir teilen Ihre persönlichen Informationen niemals mit Dritten.',
    'help.faq_5_q': 'Bei welchen Fächern kann ich Hilfe bekommen?',
    'help.faq_5_a': 'Sie können Hilfe von unserem KI-Coach in Mathematik, Naturwissenschaften, Sprachen, Geschichte und vielen anderen Fächern erhalten.',

    // Payment
    'payment.title': 'Zahlung',
    'payment.pro_title': 'Roomix Pro',
    'payment.premium_features': 'Genießen Sie Premium-Features',
    'payment.monthly_subscription': 'Monatsabonnement',
    'payment.yearly_subscription': 'Jahresabonnement',
    'payment.per_year': '/Jahr',
    'payment.features.unlimited_ai': 'Unbegrenztes KI-Coaching',
    'payment.features.premium_rooms': 'Premium-Lernräume',
    'payment.features.advanced_stats': 'Erweiterte Statistiken',
    'payment.features.ad_free': 'Werbefreie Erfahrung',
    'payment.features.priority_support': 'Prioritäts-Support',
    'payment.card_info': 'Zahlungsinformationen',
    'payment.card_holder': 'Karteninhaber',
    'payment.card_number': 'Kartennummer',
    'payment.expiry_date': 'Ablaufdatum',
    'payment.cvc': 'CVC',
    'payment.complete_payment': 'Zahlung abschließen',
    'payment.processing': 'Wird verarbeitet...',
    'payment.success_title': 'Zahlung erfolgreich! 🎉',
    'payment.success_message': 'Ihre Pro-Mitgliedschaft wurde aktiviert.',
    'payment.error_title': 'Zahlungsfehler',
    'payment.error_message': 'Zahlung fehlgeschlagen. Bitte versuchen Sie es erneut.',
    'payment.fill_all_fields': 'Bitte füllen Sie alle Felder aus',
    'payment.valid_card_number': 'Geben Sie eine gültige Kartennummer ein',
    'payment.security_info': 'Sichere Zahlung mit 256-Bit-SSL-Verschlüsselung',

    // Watch Rooms
    'watch.title': 'Watch Room',
    'watch.create_room': 'Watch Room erstellen',
    'watch.join_room': 'Raum beitreten',
    'watch.video_url': 'Video-URL',
    'watch.sync_video': 'Video synchronisieren',
    'watch.play': 'Abspielen',
    'watch.pause': 'Pausieren',
    'watch.members_watching': 'Personen schauen zu',
  },
  es: {
    // Home Screen
    'home.welcome': 'Bienvenido de nuevo,',
    'home.guest': 'Invitado',
    'home.friends_active': 'amigos activos',
    'home.quick_access': 'Acceso Rápido',
    'home.privileges': 'Privilegios',
    'home.chat_rooms': 'Salas de Chat',
    'home.chat_rooms_desc': 'Únete a chats públicos o crea salas privadas encriptadas',
    'home.study_sessions': 'Sesiones de Estudio',
    'home.study_sessions_desc': 'Rastrea el tiempo de estudio y compite con amigos',
    'home.watch_room': 'Watch Room',
    'home.watch_room_desc': 'Mira videos junto con amigos y chatea',
    'home.ai_coach': 'Mi Coach IA',
    'home.ai_study': 'Estudiar con IA',
    'home.ai_coach_desc': 'Tu asistente educativo impulsado por IA está listo para ayudarte',
    'home.ai_study_desc': 'Haz tus estudios más eficientes con el coach educativo IA y asistente de resolución de problemas',
    'home.upgrade_pro': 'Actualizar a Pro',

    // Profile Screen
    'profile.user': 'Usuario',
    'profile.rookie': 'Principiante',
    'profile.student': 'Estudiante',
    'profile.professor': 'Profesor',
    'profile.level': 'Nivel',
    'profile.xp_left': 'XP restantes',
    'profile.my_stats': 'Mis Estadísticas',
    'profile.study_hours': 'Horas de Estudio',
    'profile.messages': 'Mensajes',
    'profile.achievements': 'Logros',
    'profile.this_week': 'Esta semana',
    'profile.new': 'Nuevo',
    'profile.account_settings': 'Configuración de Cuenta',
    'profile.account_info': 'Información de Cuenta',
    'profile.notifications': 'Notificaciones',
    'profile.upgrade_pro': 'Actualizar a Pro',
    'profile.app_settings': 'Configuración de App',
    'profile.theme_settings': 'Configuración de Tema',
    'profile.language_options': 'Opciones de Idioma',
    'profile.help_support': 'Ayuda y Soporte',
    'profile.other': 'Otros',
    'profile.logout': 'Cerrar Sesión',

    // Account Settings
    'account.title': 'Configuración de Cuenta',
    'account.profile_info': 'Información del Perfil',
    'account.personal_info': 'Información Personal',
    'account.full_name': 'Nombre Completo',
    'account.enter_name': 'Ingrese su nombre',
    'account.update_profile': 'Actualizar Perfil',
    'account.security': 'Seguridad',
    'account.change_password': 'Cambiar Contraseña',
    'account.new_password': 'Nueva Contraseña',
    'account.enter_new_password': 'Ingrese su nueva contraseña',
    'account.confirm_password': 'Confirmar Contraseña',
    'account.enter_confirm_password': 'Reingrese su nueva contraseña',
    'account.update_password': 'Actualizar Contraseña',
    'account.profile_updated': 'Perfil actualizado exitosamente',
    'account.password_updated': 'Contraseña actualizada exitosamente',
    'account.passwords_not_match': 'Las nuevas contraseñas no coinciden',
    'account.password_min_length': 'La contraseña debe tener al menos 6 caracteres',
    'account.loading_error': 'Ocurrió un error al cargar la información del perfil',

    // Language Modal
    'language.select_language': 'Seleccionar Idioma',
    'language.select_app_language': 'Elige el idioma de tu aplicación',
    'language.turkish': 'Turco',
    'language.english': 'Inglés',
    'language.german': 'Alemán',
    'language.spanish': 'Español',
    'language.russian': 'Ruso',
    'language.chinese': 'Chino',
    'language.kurdish': 'Kurdo',
    'language.cancel': 'Cancelar',

    // Common
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
  },
  ru: {
    // Home Screen
    'home.welcome': 'Добро пожаловать обратно,',
    'home.guest': 'Гость',
    'home.friends_active': 'друзей активно',
    'home.quick_access': 'Быстрый доступ',
    'home.privileges': 'Привилегии',
    'home.chat_rooms': 'Чат-комнаты',
    'home.chat_rooms_desc': 'Присоединяйтесь к публичным чатам или создавайте приватные зашифрованные комнаты',
    'home.study_sessions': 'Учебные сессии',
    'home.study_sessions_desc': 'Отслеживайте время обучения и соревнуйтесь с друзьями',
    'home.watch_room': 'Watch Room',
    'home.watch_room_desc': 'Смотрите видео вместе с друзьями и общайтесь',
    'home.ai_coach': 'Мой ИИ-тренер',
    'home.ai_study': 'Учиться с ИИ',
    'home.ai_coach_desc': 'Ваш образовательный ассистент на базе ИИ готов помочь вам',
    'home.ai_study_desc': 'Сделайте обучение более эффективным с ИИ-тренером и помощником по решению задач',
    'home.upgrade_pro': 'Обновить до Pro',

    // Profile Screen
    'profile.user': 'Пользователь',
    'profile.rookie': 'Новичок',
    'profile.student': 'Студент',
    'profile.professor': 'Профессор',
    'profile.level': 'Уровень',
    'profile.xp_left': 'XP осталось',
    'profile.my_stats': 'Моя статистика',
    'profile.study_hours': 'Часы обучения',
    'profile.messages': 'Сообщения',
    'profile.achievements': 'Достижения',
    'profile.this_week': 'На этой неделе',
    'profile.new': 'Новое',
    'profile.account_settings': 'Настройки аккаунта',
    'profile.account_info': 'Информация об аккаунте',
    'profile.notifications': 'Уведомления',
    'profile.upgrade_pro': 'Обновить до Pro',
    'profile.app_settings': 'Настройки приложения',
    'profile.theme_settings': 'Настройки темы',
    'profile.language_options': 'Языковые параметры',
    'profile.help_support': 'Помощь и поддержка',
    'profile.other': 'Прочее',
    'profile.logout': 'Выйти',

    // Account Settings
    'account.title': 'Настройки аккаунта',
    'account.profile_info': 'Информация профиля',
    'account.personal_info': 'Личная информация',
    'account.full_name': 'Полное имя',
    'account.enter_name': 'Введите ваше имя',
    'account.update_profile': 'Обновить профиль',
    'account.security': 'Безопасность',
    'account.change_password': 'Изменить пароль',
    'account.new_password': 'Новый пароль',
    'account.enter_new_password': 'Введите новый пароль',
    'account.confirm_password': 'Подтвердить пароль',
    'account.enter_confirm_password': 'Повторите новый пароль',
    'account.update_password': 'Обновить пароль',
    'account.profile_updated': 'Профиль успешно обновлен',
    'account.password_updated': 'Пароль успешно обновлен',
    'account.passwords_not_match': 'Новые пароли не совпадают',
    'account.password_min_length': 'Пароль должен содержать не менее 6 символов',
    'account.loading_error': 'Произошла ошибка при загрузке информации профиля',

    // Language Modal
    'language.select_language': 'Выберите язык',
    'language.select_app_language': 'Выберите язык вашего приложения',
    'language.turkish': 'Турецкий',
    'language.english': 'Английский',
    'language.german': 'Немецкий',
    'language.spanish': 'Испанский',
    'language.russian': 'Русский',
    'language.chinese': 'Китайский',
    'language.kurdish': 'Курдский',
    'language.cancel': 'Отмена',

    // Common
    'common.cancel': 'Отмена',
    'common.save': 'Сохранить',
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успешно',
  },
  zh: {
    // Home Screen
    'home.welcome': '欢迎回来，',
    'home.guest': '访客',
    'home.friends_active': '朋友在线',
    'home.quick_access': '快速访问',
    'home.privileges': '特权',
    'home.chat_rooms': '聊天室',
    'home.chat_rooms_desc': '加入公共聊天或创建私人加密房间',
    'home.study_sessions': '学习会话',
    'home.study_sessions_desc': '跟踪学习时间并与朋友竞争',
    'home.watch_room': '观看室',
    'home.watch_room_desc': '与朋友一起观看视频并聊天',
    'home.ai_coach': '我的AI教练',
    'home.ai_study': '与AI学习',
    'home.ai_coach_desc': '您的AI驱动教育助手已准备好为您提供帮助',
    'home.ai_study_desc': '使用AI驱动的教育教练和问题解决助手让您的学习更高效',
    'home.upgrade_pro': '升级到专业版',

    // Profile Screen
    'profile.user': '用户',
    'profile.rookie': '新手',
    'profile.student': '学生',
    'profile.professor': '教授',
    'profile.level': '等级',
    'profile.xp_left': '剩余经验值',
    'profile.my_stats': '我的统计',
    'profile.study_hours': '学习时间',
    'profile.messages': '消息',
    'profile.achievements': '成就',
    'profile.this_week': '本周',
    'profile.new': '新',
    'profile.account_settings': '账户设置',
    'profile.account_info': '账户信息',
    'profile.notifications': '通知',
    'profile.upgrade_pro': '升级到专业版',
    'profile.app_settings': '应用设置',
    'profile.theme_settings': '主题设置',
    'profile.language_options': '语言选项',
    'profile.help_support': '帮助与支持',
    'profile.other': '其他',
    'profile.logout': '登出',

    // Account Settings
    'account.title': '账户设置',
    'account.profile_info': '个人资料信息',
    'account.personal_info': '个人信息',
    'account.full_name': '全名',
    'account.enter_name': '输入您的姓名',
    'account.update_profile': '更新个人资料',
    'account.security': '安全',
    'account.change_password': '更改密码',
    'account.new_password': '新密码',
    'account.enter_new_password': '输入您的新密码',
    'account.confirm_password': '确认密码',
    'account.enter_confirm_password': '重新输入您的新密码',
    'account.update_password': '更新密码',
    'account.profile_updated': '个人资料更新成功',
    'account.password_updated': '密码更新成功',
    'account.passwords_not_match': '新密码不匹配',
    'account.password_min_length': '密码至少包含6个字符',
    'account.loading_error': '加载个人资料信息时出错',

    // Language Modal
    'language.select_language': '选择语言',
    'language.select_app_language': '选择您的应用程序语言',
    'language.turkish': '土耳其语',
    'language.english': '英语',
    'language.german': '德语',
    'language.spanish': '西班牙语',
    'language.russian': '俄语',
    'language.chinese': '中文',
    'language.kurdish': '库尔德语',
    'language.cancel': '取消',

    // Common
    'common.cancel': '取消',
    'common.save': '保存',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
  },
  ku: {
    // Home Screen
    'home.welcome': 'Bi xêr hatî,',
    'home.guest': 'Mêvan',
    'home.friends_active': 'heval çalak',
    'home.quick_access': 'Gihiştina Bilez',
    'home.privileges': 'Mafên Taybetî',
    'home.chat_rooms': 'Oteyên Sohbetê',
    'home.chat_rooms_desc': 'Beşdarî sohbetên giştî bibe an jî oteyên taybet û şîfrekirî ava bike',
    'home.study_sessions': 'Danişînên Xwendinê',
    'home.study_sessions_desc': 'Demê xwendinê bişopîne û ligel hevalan pêş de here',
    'home.watch_room': 'Oteyê Temaşekirinê',
    'home.watch_room_desc': 'Ligel hevalan re vîdyo bibîne û sohbet bike',
    'home.ai_coach': 'Mamosteyê Min ê AI',
    'home.ai_study': 'Bi AI re Bixwîne',
    'home.ai_coach_desc': 'Alîkarê xwendinê yê bi teknolojiya AI amade ye ku ji te re alîkarî bike',
    'home.ai_study_desc': 'Xwendina xwe bi mamosteyê AI û alîkarê çareseriya pirsan bêtir bandor bike',
    'home.upgrade_pro': 'Berbi Pro ve Bilind bike',

    // Profile Screen
    'profile.user': 'Bikarhêner',
    'profile.rookie': 'Destpêker',
    'profile.student': 'Xwendekar',
    'profile.professor': 'Profesör',
    'profile.level': 'Ast',
    'profile.xp_left': 'XP ma',
    'profile.my_stats': 'Statistîkên Min',
    'profile.study_hours': 'Demjimêrên Xwendinê',
    'profile.messages': 'Peyam',
    'profile.achievements': 'Serkeftinên',
    'profile.this_week': 'Ev hefte',
    'profile.new': 'Nû',
    'profile.account_settings': 'Mîhengên Hesabê',
    'profile.account_info': 'Agahiyên Hesabê',
    'profile.notifications': 'Hişyariyan',
    'profile.upgrade_pro': 'Berbi Pro ve Bilind bike',
    'profile.app_settings': 'Mîhengên Sepanê',
    'profile.theme_settings': 'Mîhengên Rûkesh',
    'profile.language_options': 'Vebijarkên Zimanî',
    'profile.help_support': 'Alîkarî û Piştgirî',
    'profile.other': 'Yên Din',
    'profile.logout': 'Derketin',

    // Account Settings
    'account.title': 'Mîhengên Hesabê',
    'account.profile_info': 'Agahiyên Profîlê',
    'account.personal_info': 'Agahiyên Kesane',
    'account.full_name': 'Nav û Paşnav',
    'account.enter_name': 'Navê xwe binivîse',
    'account.update_profile': 'Profîlê Nûve bike',
    'account.security': 'Ewlehî',
    'account.change_password': 'Şîfreyê Biguhire',
    'account.new_password': 'Şîfreya Nû',
    'account.enter_new_password': 'Şîfreya xwe ya nû binivîse',
    'account.confirm_password': 'Şîfreyê Bipejirîne',
    'account.enter_confirm_password': 'Şîfreya xwe ya nû dîsa binivîse',
    'account.update_password': 'Şîfreyê Nûve bike',
    'account.profile_updated': 'Profîl bi serkeftî hat nûvekirin',
    'account.password_updated': 'Şîfre bi serkeftî hat nûvekirin',
    'account.passwords_not_match': 'Şîfreyên nû li hev nagerin',
    'account.password_min_length': 'Şîfre divê herî kêm 6 tîp be',
    'account.loading_error': 'Di barkirina agahiyên profîlê de çewtî çêbû',

    // Language Modal
    'language.select_language': 'Ziman Hilbijêre',
    'language.select_app_language': 'Zimanê sepana xwe hilbijêre',
    'language.turkish': 'Tirkî',
    'language.english': 'Îngilîzî',
    'language.german': 'Almanî',
    'language.spanish': 'Spanî',
    'language.russian': 'Rûsî',
    'language.chinese': 'Çînî',
    'language.kurdish': 'Kurdî',
    'language.cancel': 'Betal bike',

    // Common
    'common.cancel': 'Betal bike',
    'common.save': 'Tomar bike',
    'common.loading': 'Bar dibe...',
    'common.error': 'Çewtî',
    'common.success': 'Serkeftî',
    'common.delete': 'Jê bibe',
    'common.edit': 'Sererast bike',
    'common.back': 'Veger',
    'common.next': 'Pêş',
    'common.yes': 'Erê',
    'common.no': 'Na',
    'common.ok': 'Temam',

    // AI Chat
    'ai_chat.title': 'Mamosteyê AI',
    'ai_chat.greeting': 'Silav! Ez mamosteyê we yê xwendinê yê bi teknolojiya AI me. Ez dikarim ji we re di xwendin, amadekarina imtîhanan an her mijarê de alîkarî bikim. Ma ez dikarim we baştir nas bikim?',
    'ai_chat.type_message': 'Peyama xwe binivîse...',
    'ai_chat.send': 'Bişîne',
    'ai_chat.clear_chat': 'Sohbetê Pak bike',
    'ai_chat.attach_image': 'Wêne Zêde bike',
    'ai_chat.take_photo': 'Foto Bikişîne',
    'ai_chat.attach_file': 'Dosye Zêde bike',
    'ai_chat.thinking': 'Difikire...',
    'ai_chat.error_message': 'Çewtiyeke çêbû. Ji kerema xwe dîsa biceribîne.',

    // Chat Rooms
    'chat.title': 'Oteyên Sohbetê',
    'chat.public_rooms': 'Oteyên Giştî',
    'chat.private_rooms': 'Oteyên Taybet',
    'chat.create_room': 'Oteyek Ava bike',
    'chat.join_room': 'Beşdarî Oteyê bibe',
    'chat.room_name': 'Navê Oteyê',
    'chat.room_description': 'Danasîna Oteyê',
    'chat.room_password': 'Şîfreya Oteyê',
    'chat.is_private': 'Oteyê Taybet',
    'chat.active_room': 'Oteyê Çalak',
    'chat.encrypted': 'Şîfrekirî',
    'chat.members': 'endaman',
    'chat.search_rooms': 'Li oteyan bigere...',
    'chat.no_rooms': 'Di vê kategoriyê de hîn oteyek tune',
    'chat.delete_room': 'Oteyê Jê bibe',
    'chat.leave_room': 'Ji Oteyê Derkeve',
    'chat.enter_password': 'Şîfreyê binivîse',

    // Study Rooms
    'study.title': 'Oteyên Xwendinê',
    'study.personal_timer': 'Demjimêrê Kesane',
    'study.create_room': 'Oteyê Xwendinê Ava bike',
    'study.join_room': 'Beşdarî Oteyê bibe',
    'study.start_timer': 'Dest pê bike',
    'study.pause_timer': 'Rawestîne',
    'study.resume_timer': 'Dom bike',
    'study.stop_timer': 'Bisekinîne',
    'study.reset_timer': 'Ji nû ve saz bike',
    'study.study_session': 'Danişîna Xwendinê',
    'study.total_time': 'Dema Giştî',
    'study.active_members': 'çalak',
    'study.room_description': 'Oteyê xwendinê',
    'study.private_room': 'Oteyê Taybet',
    'study.public_rooms': 'Oteyên Giştî',
    'study.private_rooms': 'Oteyên Taybet',
    'study.no_rooms': 'Di vê kategoriyê de hîn oteyek tune',

    // Help & Support
    'help.title': 'Alîkarî û Piştgirî',
    'help.welcome_title': 'Em Çawa Dikarin Ji We re Alîkarî Bikin?',
    'help.welcome_desc': 'Pirsên we hene an jî pirsgirêkên we hene? Em bi kêfxweşiyê ji we re alîkarî dikin. Hûn dikarin ji rêyên jêrîn bi me re têkilî daynin.',
    'help.email': 'E-posta',
    'help.live_support': 'Piştgiriya Zindî',
    'help.live_support_desc': 'Piştgiriya Chat 7/24',
    'help.website': 'Malper',
    'help.phone': 'Telefon',
    'help.faq_title': 'Pirsên Pir Tên Pirsîn',
    'help.faq_1_q': 'Mamosteyê AI çawa dixebite?',
    'help.faq_1_a': 'Mamosteyê me yê AI pirsên we analîz dike û pêşniyarên xwendina kesane pêşkêş dike. Plansaziyên xwendinê çêdike û ji we re dibe alîkar ku mijar fêm bikin.',
    'help.faq_2_q': 'Oteyên xwendinê çawa tên bikaranîn?',
    'help.faq_2_a': 'Bi beşdarbûna oteyên xwendinê hûn dikarin ligel hevalan re bixwînin, dem bişopînin û bi hev re motîvasyonê biparêzin.',
    'help.faq_3_q': 'Endamtiya Pro çi feydeyên pêşkêş dike?',
    'help.faq_3_a': 'Bi endamtiya Pro hûn mamosteyiya AI ya bêsînor, oteyên xwendina pro, statîstîkên pêşketî û ezmûnek bê reklaman bistînin.',
    'help.faq_4_q': 'Daneyên min ewle ne?',
    'help.faq_4_a': 'Erê, hemû daneyên we bi şîfrekirina SSL ya 256-bit tên parastin. Em qet agahiyên we yên kesane bi kesên din re parve nakin.',
    'help.faq_5_q': 'Li ser kîjan mijaran ez dikarim alîkarî bistînim?',
    'help.faq_5_a': 'Hûn dikarin ji mamosteyê me yê AI li ser matematîk, zanistên tebîî, zimannasî, dîrok û gelek mijarên din alîkarî bistînin.',

    // Payment
    'payment.title': 'Dravdan',
    'payment.pro_title': 'Roomix Pro',
    'payment.premium_features': 'Ji taybetmendiyên premium kêf bistînin',
    'payment.monthly_subscription': 'Abonetiya mehane',
    'payment.yearly_subscription': 'Abonetiya salane',
    'payment.per_year': '/sal',
    'payment.features.unlimited_ai': 'Mamosteyiya AI ya Bêsînor',
    'payment.features.premium_rooms': 'Oteyên Xwendina Premium',
    'payment.features.advanced_stats': 'Statîstîkên Pêşketî',
    'payment.features.ad_free': 'Ezmûnek Bê Reklaman',
    'payment.features.priority_support': 'Piştgiriya Pêşîn',
    'payment.card_info': 'Agahiyên Dravdanê',
    'payment.card_holder': 'Navê Xwediyê Kartê',
    'payment.card_number': 'Hejmara Kartê',
    'payment.expiry_date': 'Dîroka Dawîbûnê',
    'payment.cvc': 'CVC',
    'payment.complete_payment': 'Dravdanê Temam bike',
    'payment.processing': 'Tê pêvajokirin...',
    'payment.success_title': 'Dravdan Serkeftî! 🎉',
    'payment.success_message': 'Endamtiya we ya Pro hat çalakkirin.',
    'payment.error_title': 'Çewtiya Dravdanê',
    'payment.error_message': 'Dravdan têk çû. Ji kerema xwe dîsa biceribîne.',
    'payment.fill_all_fields': 'Ji kerema xwe hemû zeviyên dagirin',
    'payment.valid_card_number': 'Hejmarek kartê ya derbasdar binivîse',
    'payment.security_info': 'Dravdana ewle bi şîfrekirina SSL ya 256-bit',

    // Watch Rooms
    'watch.title': 'Oteyê Temaşekirinê',
    'watch.create_room': 'Oteyê Temaşekirinê Ava bike',
    'watch.join_room': 'Beşdarî Oteyê bibe',
    'watch.video_url': 'Lînka Vîdyoyê',
    'watch.sync_video': 'Vîdyoyê Hevdem bike',
    'watch.play': 'Lêdan',
    'watch.pause': 'Rawestîne',
    'watch.members_watching': 'kes temaşe dike',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('tr');

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem('app_language');
      if (savedLanguage && ['tr', 'en', 'de', 'es', 'ru', 'zh', 'ku'].includes(savedLanguage)) {
        setLanguageState(savedLanguage as Language);
      }
    } catch (error) {
      console.error('Error loading language:', error);
    }
  };

  const setLanguage = async (newLanguage: Language) => {
    try {
      await AsyncStorage.setItem('app_language', newLanguage);
      setLanguageState(newLanguage);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  const t = (key: string, params?: Record<string, string>): string => {
    let translation = translations[language][key as keyof typeof translations[typeof language]] || key;
    
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{{${param}}}`, params[param]);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 